/**
 * Toasts end to end (`08-feedback` FB4 §6, §9, FB8; spec redesign D0-5; INV-6, A-24, X9):
 * - a damaged file shows a visible failure toast that stays until dismissed (INV-6: it used to
 *   be spoken only);
 * - deleting a page shows "Deleted page 2 · Undo", held for at least 10 s while hovered, reached
 *   by F6 as the last region, and its Undo brings the page back;
 * - screenshots of the stack at 1440 × 900 in English and Turkish (looked at by the author;
 *   the pinned baselines are the lead's, Q-13).
 *
 * The compact edition's placement (above the capsule) is in `compact.spec.ts`, the one spec the
 * phone projects run.
 *
 * Engine-agnostic: the damaged file is generated bytes that no engine can parse.
 */
import { expect, type Page, test } from '@playwright/test';

import { openFixtures, useFileInputPicker } from './helpers';

test.use({ viewport: { width: 1440, height: 900 } });

const SHOTS = process.env.TOAST_SHOTS;

test.beforeEach(async ({ page }, info) => {
  test.skip(
    ['phone', 'phone-land'].includes(info.project.name),
    'the compact edition’s toast is tested in compact.spec.ts',
  );
  await useFileInputPicker(page);
});

/** A file named like a PDF whose bytes are not one. */
const DAMAGED = {
  name: 'scan.pdf',
  mimeType: 'application/pdf',
  buffer: Buffer.from(`%PDF-1.7\n${'damaged '.repeat(64)}\n%%EOF\n`),
};

async function openDamaged(page: Page): Promise<void> {
  const chooser = page.waitForEvent('filechooser');
  await page
    .getByRole('button', { name: /^(Open files|Dosya aç)$/ })
    .first()
    .click();
  await (await chooser).setFiles(DAMAGED);
}

async function deleteSecondPage(page: Page): Promise<void> {
  await page.keyboard.press('3');
  const cells = page.locator('[role="gridcell"][data-page-id]');
  await expect(cells).toHaveCount(3);
  await cells.nth(1).click();
  await page.keyboard.press('Delete');
  await expect(cells).toHaveCount(2);
}

test('a damaged file shows a visible failure toast until it is dismissed (INV-6)', async ({
  page,
}) => {
  await page.goto('./?lang=en');
  await openDamaged(page);
  const toast = page.getByRole('group', { name: 'Could not open scan.pdf: the file is damaged.' });
  await expect(toast).toBeVisible();
  await expect(page.getByRole('region', { name: 'Notifications' })).toContainText(
    'Could not open scan.pdf: the file is damaged.',
  );
  // A failure stays (no timer): still there well after an info toast would have gone.
  await page.waitForTimeout(5_000);
  await expect(toast).toBeVisible();
  await toast.getByRole('button', { name: 'Dismiss' }).click();
  await expect(toast).toHaveCount(0);
});

test('"Deleted page 2 · Undo" holds while hovered, F6 reaches it, and Undo brings the page back', async ({
  page,
}) => {
  await page.goto('./?lang=en');
  await openFixtures(page, ['simple-text.pdf']);
  await deleteSecondPage(page);
  const toast = page.getByRole('group', { name: 'Deleted page 2' });
  await expect(toast).toBeVisible();

  // A-24: held on hover well past its 10 s.
  await toast.hover();
  await page.waitForTimeout(11_000);
  await expect(toast).toBeVisible();
  await page.mouse.move(2, 450);

  // X9: the region is the last F6 stop, so Shift+F6 from the first region lands on Undo.
  await page.getByRole('tab', { name: 'simple-text' }).focus();
  await page.keyboard.press('Shift+F6');
  await expect(toast.getByRole('button', { name: 'Undo' })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.locator('[role="gridcell"][data-page-id]')).toHaveCount(3);
  await expect(toast).toHaveCount(0);
});

test('a toast stays readable above a modal sheet and its scrim', async ({ page }, info) => {
  // 07-sheets §1.1 rule 6: … scrim → modal sheets → toasts. A toast under the scrim was dimmed
  // and could not be read while the sheet it was about stayed open (task 27).
  await page.goto('./?lang=en');
  await openFixtures(page, ['simple-text.pdf']);
  await deleteSecondPage(page);
  const toast = page.getByRole('group', { name: 'Deleted page 2' });
  await expect(toast).toBeVisible();
  await page.locator('body').press('?');
  const sheet = page.getByRole('dialog', { name: 'Keyboard shortcuts' });
  await expect(sheet).toBeVisible();
  // A modal pauses the toast's timer (FB4 §4), so it is still there, and on top: the element
  // drawn at its centre is the toast's own. (The modal hides the rest of the page from the
  // accessibility tree, so the toast is found by its markup here.)
  const shown = page.locator('[data-region="toasts"] [data-toast-id]', {
    hasText: 'Deleted page 2',
  });
  await expect(shown).toBeVisible();
  const box = await shown.boundingBox();
  if (!box) throw new Error('the toast has no box');
  const onTop = await page.evaluate(
    ({ x, y }) => document.elementFromPoint(x, y)?.closest('[data-toast-id]')?.textContent ?? null,
    { x: box.x + 24, y: box.y + box.height / 2 },
  );
  expect(onTop).toContain('Deleted page 2');
  if (SHOTS && info.project.name === 'chromium') {
    await page.waitForTimeout(400);
    await page.screenshot({ path: `${SHOTS}/toast-over-sheet-1440.png` });
  }
});

for (const lang of ['en', 'tr'] as const) {
  test(`the stack at 1440 × 900 (${lang})`, async ({ page }, info) => {
    test.skip(!SHOTS || info.project.name !== 'chromium', 'screenshots on request (TOAST_SHOTS)');
    await page.goto(`./?lang=${lang}`);
    await openFixtures(page, ['simple-text.pdf']);
    await openDamaged(page);
    await deleteSecondPage(page);
    await page.mouse.move(2, 450);
    await page.waitForTimeout(600);
    await page.screenshot({ path: `${SHOTS}/toasts-${lang}-1440.png` });
    await page
      .getByRole('group')
      .filter({ hasText: /scan\.pdf/ })
      .hover();
    await page.waitForTimeout(300);
    await page.screenshot({
      path: `${SHOTS}/toasts-${lang}-hover.png`,
      clip: { x: 360, y: 560, width: 720, height: 340 },
    });
  });
}
