/**
 * The coverage registry (docs/specs/redesign.md §6 X24, D0-1 and D3-3; language.md §2.9, A-2;
 * components/09-primitives.md §26, §27): one entry per glass surface, at the smallest size it
 * renders at, with its material tier and its blur σ. Three things are made from it:
 *
 * - `materials.css`, generated by `tooling/materials.ts` (`styles/materials-css.ts`): one rule
 *   per tier × σ the entries use, the `-webkit-` line and the unprefixed one with equal literal
 *   values (G-22), so the CSS and this list cannot drift (`materials.test.ts`);
 * - `tokens.test.ts`'s coverage term for each entry, at each size it names,
 *
 *     c = erf(h / 2√2σ) · erf(w / 2√2σ) ≥ 0.985,
 *
 *   and the check that every module rule composing a material is registered here with exactly
 *   the classes its entries give (and nothing else is);
 * - the rendered-pixel harness (`harness/main.tsx`, `e2e/glass-pixels.spec.ts`), which draws
 *   each entry at its smallest size over known backdrops.
 *
 * Why the term: a backdrop blur that is large against a surface's size takes its samples from
 * beyond the surface, where nothing is blurred, so the unfiltered page shows through the edges
 * in proportion 1 − c (research 22 §3.2: the 44 px bar at blur 28px rendered #5b5d61 over a
 * white page instead of the model's #47494d, and its secondary text fell from 4.9:1 to 3.6:1).
 * At c ≥ 0.985 the rendered glass stays within about 2/255 of the model the contrast tests use.
 *
 * Where content sets a size, `minWidth` / `minHeight` are a lower bound of what renders (the
 * walker in `e2e/support/glass-walker.ts` checks the same rule on the rendered sizes); fixed
 * sizes are exact. Heights include the 1 px rim. σ comes from language.md §2.2's steps, the
 * largest the smallest size allows where the tier's own value would leak (the menus' 12 below
 * 92 px, the sheets' 24 below 260 px, the sidebar's 24 at its 200 px minimum).
 */
import type { GlassTier } from './token-registry';

/** The σ steps `materials.css` may hold (09-primitives §26). */
export const SIGMA_STEPS: readonly number[] = [5, 6, 7, 8, 9, 10, 12, 16, 20, 24, 40, 48];

/** A σ at another size: the coarse pointer's density, or compact-height (`:root[data-short]`). */
export interface SizedSigma {
  readonly sigma: number;
  readonly minWidth: number;
  readonly minHeight: number;
}

export interface GlassSurfaceEntry {
  /** Stable id, kebab case. */
  readonly id: string;
  /** What a person calls it. */
  readonly surface: string;
  /** The CSS module, relative to `src/`. */
  readonly module: string;
  /** The module class whose rule composes the material (`.toolbar`). */
  readonly selector: string;
  /** Its tier (language.md §2.2): M1 chip to M5 sheet. */
  readonly tier: GlassTier;
  /** Docked M3 (language.md §2.4): the module draws the hairline on its free edge; no shadow. */
  readonly docked?: true;
  /** σ on a fine pointer, CSS px: the class `s<σ>`. */
  readonly sigma: number;
  /** σ on a coarse pointer (`c<σ>`), or `'solid'` (`cs`: solid on a coarse pointer, M-31). */
  readonly coarse?: SizedSigma | 'solid';
  /** σ in compact-height (`h<σ>`, the capsule's 44 px dock at 8). */
  readonly short?: SizedSigma;
  /**
   * The one-row form of a menu (`r<σ>`): the same rule as the entry before it, applied while the
   * surface holds a single child (`:not(:has(> :nth-child(2)))`), too short for the menus' σ.
   */
  readonly oneRow?: true;
  /** A fixed-size M1 chip that takes the backdrop lens on Chromium (language.md §2.7, X20). */
  readonly lens?: true;
  /** Smallest rendered width and height on a fine pointer, CSS px. */
  readonly minWidth: number;
  readonly minHeight: number;
  /** Where that smallest size comes from. */
  readonly smallest: string;
}

/** The global classes an entry composes: `mat mat-<tier> [mat-docked] s<σ> [c<σ>|cs] [h<σ>]`. */
export function entryClasses(entry: GlassSurfaceEntry): string[] {
  if (entry.oneRow) return [`r${entry.sigma}`];
  const classes = ['mat', `mat-${entry.tier}`];
  if (entry.docked) classes.push('mat-docked');
  classes.push(`s${entry.sigma}`);
  if (entry.coarse === 'solid') classes.push('cs');
  else if (entry.coarse) classes.push(`c${entry.coarse.sigma}`);
  if (entry.short) classes.push(`h${entry.short.sigma}`);
  return classes;
}

/**
 * What a module rule composes: the classes of every entry registered on it, in order (a menu's
 * one-row form adds its `r<σ>` to the menu's own classes).
 */
export function compositionOf(module: string, selector: string): string[] {
  const classes: string[] = [];
  for (const entry of COVERAGE_REGISTRY) {
    if (entry.module !== module || entry.selector !== selector) continue;
    for (const name of entryClasses(entry)) if (!classes.includes(name)) classes.push(name);
  }
  return classes;
}

export const COVERAGE_REGISTRY: readonly GlassSurfaceEntry[] = [
  {
    id: 'capsule',
    surface: 'Capsule: the dock, the Markup palette and Locked (spec X1)',
    module: 'shell/capsule/Capsule.module.css',
    selector: '.capsule',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 240, minHeight: 48 },
    short: { sigma: 8, minWidth: 240, minHeight: 40 },
    minWidth: 240,
    minHeight: 40,
    smallest:
      '--piece-h, 40 px fine (48 coarse; 56 with labels under); Pages · Locked · More with labels under is the narrowest (about 240 px)',
  },
  {
    id: 'strip-piece',
    surface: "Markup palette's floating ink strip (owner feedback F3; the capsule's material)",
    module: 'markup/StripPiece.module.css',
    selector: '.piece',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 200, minHeight: 48 },
    short: { sigma: 8, minWidth: 160, minHeight: 40 },
    minWidth: 160,
    minHeight: 40,
    smallest:
      '--piece-h, 40 px fine (48 coarse), hugging its content: the narrowest strip is its colours row (four 32 px swatches and the well, 44 px targets coarse) in --piece-pad and the 1 px rim',
  },
  {
    id: 'read-selection-bar',
    surface: 'Text selection bar',
    module: 'annotations/ReadSelectionBar.module.css',
    selector: '.bar',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 160, minHeight: 48 },
    minWidth: 120,
    minHeight: 40,
    smallest: '--piece-h, 40 px on a fine pointer (G1, D0-3, Q-9); Copy and the markups',
  },
  {
    id: 'annotation-bar',
    surface: 'Annotation contextual bar',
    module: 'annotations/AnnotationLayer.module.css',
    selector: '.bar',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 200, minHeight: 48 },
    minWidth: 160,
    minHeight: 40,
    smallest: '--piece-h, 40 px on a fine pointer (G1, D0-3, Q-9)',
  },
  {
    id: 'note-popup',
    surface: 'Note popup',
    module: 'annotations/AnnotationLayer.module.css',
    selector: '.notePopup',
    tier: 'menu',
    sigma: 16,
    minWidth: 240,
    minHeight: 120,
    smallest: '240 px wide; author line, an empty text area and the actions',
  },
  {
    id: 'image-bar',
    surface: 'Image contextual bar',
    module: 'image-objects/ImageObjects.module.css',
    selector: '.bar',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 200, minHeight: 48 },
    minWidth: 160,
    minHeight: 40,
    smallest: '--piece-h, 40 px on a fine pointer (G1, D0-3, Q-9)',
  },
  {
    id: 'form-notice',
    surface: 'Form field notice',
    module: 'forms/FormLayer.module.css',
    selector: '.notice',
    tier: 'bar',
    sigma: 9,
    minWidth: 180,
    minHeight: 54,
    smallest: 'min-width 180 px; a title and one line',
  },
  {
    id: 'form-lock-notice',
    surface: "Read's form lock notice",
    module: 'forms/FormLayer.module.css',
    selector: '.lockNotice',
    tier: 'bar',
    sigma: 7,
    minWidth: 160,
    minHeight: 36,
    smallest: '5 px around its 24 px Edit button, the border: 36 px (was 34 px, c 0.9848 at 7px)',
  },
  {
    id: 'grid-piece',
    surface: 'Pages grid scope and size pieces (06-navigation PG2; owner feedback F1)',
    module: 'stage/grid/GridPieces.module.css',
    selector: '.piece',
    tier: 'bar',
    sigma: 7,
    coarse: { sigma: 8, minWidth: 48, minHeight: 48 },
    minWidth: 40,
    minHeight: 40,
    smallest: 'folded to a circle of --bar-h beside a wide Pages bar: 40 × 40 fine, 48 × 48 coarse',
  },
  {
    id: 'crop-banner',
    surface: 'Crop banner',
    module: 'crop/Crop.module.css',
    selector: '.banner',
    tier: 'bar',
    sigma: 7,
    coarse: { sigma: 8, minWidth: 200, minHeight: 48 },
    minWidth: 200,
    minHeight: 40,
    smallest: 'a floating piece of --piece-h: 40 fine, 48 coarse',
  },
  {
    id: 'compare-toolbar',
    surface: 'Compare tool bar',
    module: 'compare/CompareView.module.css',
    selector: '.toolbar',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 200, minHeight: 48 },
    minWidth: 160,
    minHeight: 40,
    smallest: '32 px buttons, 3 px padding, the border: 40 px (G1, D0-3, Q-9)',
  },
  {
    id: 'compare-progress',
    surface: 'Compare progress card',
    module: 'compare/CompareView.module.css',
    selector: '.progress',
    tier: 'bar',
    sigma: 10,
    minWidth: 288,
    minHeight: 60,
    smallest: 'min(420 px, the stage less 32 px); a label, the bar and Cancel',
  },
  {
    id: 'command-palette',
    surface: 'Command palette',
    module: 'shell/CommandPalette.module.css',
    selector: '.popup',
    tier: 'menu',
    sigma: 24,
    minWidth: 288,
    minHeight: 140,
    smallest: 'min(600 px, the window less 32 px); the search row, an empty list, the footer',
  },
  {
    id: 'menu',
    surface: 'Menus and context menus',
    module: 'ui/Menu.module.css',
    selector: '.popup',
    tier: 'menu',
    sigma: 12,
    minWidth: 200,
    minHeight: 78,
    smallest: 'min-width 200 px; two 32 px rows, 6 px padding, the border: 78 px',
  },
  {
    id: 'menu-one-row',
    surface: 'One-row menu',
    module: 'ui/Menu.module.css',
    selector: '.popup',
    tier: 'menu',
    sigma: 8,
    oneRow: true,
    minWidth: 200,
    minHeight: 46,
    smallest: "Recents' Remove: one 32 px row, 6 px padding, the border: 46 px",
  },
  {
    id: 'popover',
    surface: 'Popovers',
    module: 'ui/Popover.module.css',
    selector: '.popup',
    tier: 'menu',
    sigma: 12,
    minWidth: 288,
    minHeight: 72,
    smallest: 'min(320 px, the window less 16 px); a title and one line',
  },
  {
    id: 'sheet-side',
    surface: 'Side sheet (tool, task, Settings)',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 304, minHeight: 200 },
    minWidth: 304,
    minHeight: 200,
    smallest:
      'min(360 px, the window less 16 px) on a compact-height window; its height there less the title bar and 16 px',
  },
  {
    id: 'sheet-form',
    surface: 'Form sheet',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 568, minHeight: 160 },
    minWidth: 568,
    minHeight: 160,
    smallest:
      "min(640 px, the window less 32 px) at the medium class's 600 px; a header, one row and the footer",
  },
  {
    id: 'sheet-dialog',
    surface: 'Centred dialog and confirmation',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 288, minHeight: 168 },
    minWidth: 288,
    minHeight: 168,
    smallest:
      "min(400 px, the window less 32 px) at 320 px; 07-sheets §2.2's shortest confirmation",
  },
  {
    id: 'sheet-overlay',
    surface: 'Shortcuts overlay',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 536, minHeight: 240 },
    minWidth: 536,
    minHeight: 240,
    smallest: "min(760 px, the window less 64 px) at the medium class's 600 px",
  },
  {
    id: 'sheet-bottom',
    surface: 'Bottom sheet',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 320, minHeight: 140 },
    minWidth: 320,
    minHeight: 140,
    smallest:
      "the window's 320 px; the shortest compact confirmation (the bleed below the window not counted)",
  },
  {
    id: 'sheet-full',
    surface: 'Full sheet',
    module: 'ui/sheet/Sheet.module.css',
    selector: '.panel',
    tier: 'sheet',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 320, minHeight: 248 },
    minWidth: 320,
    minHeight: 248,
    smallest: 'a 320 × 256 window (A-20) under the 8 px top inset',
  },
  {
    id: 'compact-top-bar',
    surface: 'Compact edition top bar',
    module: 'shell/compact/CompactChrome.module.css',
    selector: '.topBar',
    tier: 'panel',
    docked: true,
    sigma: 8,
    minWidth: 320,
    minHeight: 45,
    smallest: 'a 44 px row and its bottom border on a 320 px phone (more with a safe area)',
  },
  {
    id: 'compact-capsule',
    surface: 'Compact edition bottom capsule',
    module: 'shell/compact/CompactChrome.module.css',
    selector: '.capsule',
    tier: 'bar',
    sigma: 10,
    minWidth: 120,
    minHeight: 56,
    smallest: '56 px fixed; two 44 px controls at the least',
  },
  {
    id: 'compact-menu',
    surface: 'Compact edition ⋯ menu',
    module: 'shell/compact/CompactChrome.module.css',
    selector: '.menu',
    tier: 'menu',
    sigma: 12,
    minWidth: 232,
    minHeight: 102,
    smallest: 'min-width 232 px; two 44 px rows, 6 px padding, the border: 102 px',
  },
  {
    id: 'compact-menu-one-row',
    surface: 'Compact edition one-row menu',
    module: 'shell/compact/CompactChrome.module.css',
    selector: '.menu',
    tier: 'menu',
    sigma: 8,
    oneRow: true,
    minWidth: 232,
    minHeight: 58,
    smallest: 'one 44 px row, 6 px padding, the border: 58 px',
  },
  {
    id: 'compact-sheet',
    surface: 'Compact edition bottom sheet',
    module: 'shell/compact/CompactSheet.module.css',
    selector: '.sheet',
    tier: 'sheet',
    sigma: 20,
    minWidth: 320,
    minHeight: 140,
    smallest: 'the shortest sheet (Go to page): its handle, title and one field',
  },
  {
    id: 'compact-note-popover',
    surface: 'Compact edition note popover',
    module: 'shell/compact/NoteLayer.module.css',
    selector: '.popup',
    tier: 'menu',
    sigma: 12,
    minWidth: 296,
    minHeight: 96,
    smallest: 'min(320 px, the window less 24 px); its header with Close and one line',
  },
  {
    id: 'top-strip',
    surface: 'Top strip: its two floating pieces (01-frame F2; owner feedback F1)',
    module: 'shell/frame/TopStrip.module.css',
    selector: '.piece',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 100, minHeight: 48 },
    minWidth: 80,
    minHeight: 40,
    smallest:
      '--piece-h, 40 px fine (48 coarse, G1, Q-9); the leading piece on the Library, ◆ Library and +: 80 px wide (100 coarse)',
  },
  {
    id: 'top-strip-solo',
    surface: 'Top strip: a piece of one control, the Library’s ⋯ (R11)',
    module: 'shell/frame/TopStrip.module.css',
    selector: '.solo',
    tier: 'bar',
    sigma: 7,
    coarse: { sigma: 8, minWidth: 48, minHeight: 48 },
    minWidth: 40,
    minHeight: 40,
    smallest: 'a --piece-h circle: 40 × 40 fine, 48 × 48 coarse (G1)',
  },
  {
    id: 'original-pill',
    surface: '“Markup hidden · Show markup”, under the strip (PLAN.md S2-1a)',
    module: 'shell/frame/OriginalPill.module.css',
    selector: '.pill',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 200, minHeight: 48 },
    minWidth: 180,
    minHeight: 40,
    smallest: '--piece-h high; the glyph, the shortest label and an S button: about 180 px wide',
  },
  {
    id: 'compact-frame-bar',
    surface: 'Compact top bar of the full edition (01-frame F9)',
    module: 'shell/frame/CompactTopBar.module.css',
    selector: '.bar',
    tier: 'panel',
    docked: true,
    sigma: 8,
    minWidth: 200,
    minHeight: 44,
    smallest: '44 px fixed; the short-viewport capsule at 320 × 256 is about 200 px wide',
  },
  {
    id: 'page-pill',
    surface: 'Page pill (01-frame F11)',
    module: 'shell/frame/PagePill.module.css',
    selector: '.pill',
    tier: 'chip',
    sigma: 7,
    coarse: { sigma: 8, minWidth: 96, minHeight: 48 },
    lens: true,
    minWidth: 96,
    minHeight: 40,
    smallest: '--piece-h, 40 px fine (48 coarse); "1 / 1 · 50%" with 16 px padding',
  },
  {
    id: 'navigator',
    surface: 'Sidebar (06-navigation N1; floating, overlay 320, side sheet 360; DSN-22)',
    module: 'shell/sidebar/Sidebar.module.css',
    selector: '.sidebar',
    tier: 'panel',
    sigma: 24,
    coarse: { sigma: 20, minWidth: 240, minHeight: 200 },
    minWidth: 240,
    minHeight: 200,
    smallest: 'the floating sidebar at its 240 px minimum width',
  },
  {
    id: 'toast',
    surface: 'Toast and progress capsule (08-feedback FB4, FB5)',
    module: 'ui/Toast/Toast.module.css',
    selector: '.toast',
    tier: 'bar',
    sigma: 8,
    minWidth: 240,
    minHeight: 40,
    smallest:
      'the progress capsule: 40 px fine, at least 240 px wide; a toast is 48 px and 360 px (one surface each, at most three)',
  },
  {
    id: 'pinch-detent-chip',
    surface: 'Pinch detent chip (05-canvas §4, 05.11)',
    module: 'stage/PinchDetentChip.module.css',
    selector: '.chip',
    tier: 'chip',
    sigma: 7,
    coarse: { sigma: 8, minWidth: 200, minHeight: 44 },
    minWidth: 200,
    minHeight: 36,
    smallest: '36 px fine (44 coarse); "Release to see all pages" with its icon is about 200 px',
  },
  {
    id: 'library-selection-bar',
    surface: 'Library selection bar (02-library L6)',
    module: 'home/SelectionBar.module.css',
    selector: '.bar',
    tier: 'bar',
    sigma: 8,
    coarse: { sigma: 9, minWidth: 280, minHeight: 48 },
    minWidth: 280,
    minHeight: 40,
    smallest:
      '--piece-h, 40 px fine (48 coarse); a narrow window drops the count: Combine, Compare, Pages, Close, ✕',
  },
];
