/**
 * The scale gate's ratchet (`css-scale.test.ts`; system-audit-2026-10 §3.11 gate 1): each
 * style sheet's literals off the token scales, counted per kind, as they stood when the gate
 * arrived. It may only shrink: when a lane moves a file onto the tokens, it lowers or deletes
 * that file's line. One line per file, so lanes rebasing onto each other touch separate lines.
 */
import type { ScaleKind } from './css-scale';

export const CSS_SCALE_ALLOW: Readonly<Record<string, Partial<Record<ScaleKind, number>>>> = {
  'annotations/AnnotationLayer.module.css': { radius: 1, icon: 2, stroke: 5 },
  'annotations/AnnotationProperties.module.css': { weight: 1 },
  'annotations/lasso/Lasso.module.css': { radius: 1, duration: 1, stroke: 5 },
  'annotations/pen/PenWell.module.css': { radius: 2 },
  'batch/Batch.module.css': { 'font-size': 1, icon: 2 },
  'compare/ChangesPanel.module.css': { uppercase: 1 },
  'compare/CompareView.module.css': { radius: 1, stroke: 2 },
  'document/DocumentInfoSheet.module.css': { weight: 1 },
  'document/DocumentTools.module.css': { weight: 1, icon: 2, spacing: 1 },
  'export/ExportDialog.module.css': { radius: 1, uppercase: 1, spacing: 1 },
  'export/SaveCopySheet.module.css': { duration: 2 },
  'forms/FormLayer.module.css': { icon: 2, spacing: 2 },
  'forms/create/CreatedFields.module.css': { icon: 4 },
  'home/Aura.module.css': { duration: 5 },
  'home/DropOverlay.module.css': { radius: 1 },
  'home/Launcher.module.css': { radius: 1 },
  'home/LibraryCard.module.css': { radius: 1 },
  'home/LibraryGrid.module.css': { radius: 1 },
  'home/RecentList.module.css': { radius: 1 },
  'image-objects/ImageObjects.module.css': { icon: 2 },
  'markup/InkStrip.module.css': { 'font-size': 1 },
  'markup/MarkupPalette.module.css': { uppercase: 1, spacing: 1 },
  'ocr/Ocr.module.css': { weight: 1 },
  'outline/Outline.module.css': { icon: 2 },
  'pages-sheets/PagesSheets.module.css': { radius: 1, weight: 1 },
  'privacy/PrivacyShield.module.css': { 'font-size': 1, stroke: 1, uppercase: 1, spacing: 1 },
  'redaction/ApplySheet.module.css': { weight: 1 },
  'redaction/RedactionLayer.module.css': { stroke: 4 },
  'session/KeptOnDevice.module.css': { uppercase: 1 },
  'settings/Settings.module.css': { 'font-size': 1, radius: 1, duration: 3, spacing: 1 },
  'shell/CommandPalette.module.css': { stroke: 1 },
  'shell/CommentsPanel.module.css': { icon: 2 },
  'shell/FormsPanel.module.css': { icon: 8 },
  'shell/OutlinePanel.module.css': { icon: 2 },
  'shell/frame/Dock.module.css': { spacing: 1 },
  'shell/frame/SaveButton.module.css': { duration: 4, spacing: 1 },
  'shell/frame/TopStrip.module.css': { stroke: 1 },
  'shell/panels/RedactionsPanel.module.css': { icon: 2 },
  'shell/review/ReviewPanel.module.css': { radius: 1, weight: 2 },
  'shell/sidebar/FindSection.module.css': { radius: 2 },
  'shell/sidebar/Sidebar.module.css': { radius: 1 },
  'shell/sidebar/ThumbnailList.module.css': { radius: 2, icon: 2 },
  'signatures/SignaturePlate.module.css': { spacing: 1 },
  'signatures/Signatures.module.css': { weight: 2, icon: 4, spacing: 1 },
  'text-edit/ParagraphEditor.module.css': { radius: 1 },
  'text-edit/TextEdit.module.css': { icon: 2 },
  'tools/ToolDialog.module.css': { radius: 1, spacing: 1 },
  'ui/Avatar.module.css': { icon: 2 },
  'ui/Badge.module.css': { spacing: 1 },
  'ui/Chip.module.css': { stroke: 1 },
  'ui/Field.module.css': { radius: 1 },
  'ui/Keycaps.module.css': { spacing: 2 },
  'ui/Notice.module.css': { weight: 1 },
  'ui/NumberField.module.css': { radius: 1, icon: 2, spacing: 1 },
  'ui/ScrollArea.module.css': { radius: 1 },
  'ui/Switch.module.css': { icon: 2 },
  'ui/Toast/Toast.module.css': { spacing: 1 },
  'ui/colour/ColourGrid.module.css': { spacing: 1 },
};
